services:
   #Frontend (Vite + React)services:
  frontend:
    build: ./frontend  # La ruta del frontend
    container_name: WEB_BAR_TFG_frontend  # Nombre del contenedor
    ports:
      - "5173:5173"  
    volumes:
      - ./frontend:/app  # Sincroniza el código fuente local con el contenedor (para desarrollo en vivo)
      - /app/node_modules  # Evita conflictos de dependencias entre el host y el contenedor
    working_dir: /app  # Directorio de trabajo dentro del contenedor
    command: npm run dev -- --host  # Comando para iniciar el servidor de desarrollo de Vite
    environment:
      - NODE_ENV=development  # Establece el entorno como desarrollo
    depends_on:
      - backend  # Asegura que el backend esté listo antes de arrancar el frontend
    networks:
      - bar_network  # Red compartida entre frontend y backend


  # Backend (Node.js + Express)
  backend:
    build: ./backend
    container_name: WEB_BAR_TFG_backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    networks:
      - bar_network

  # Base de datos (PostgreSQL)
  db:
    image: postgres:latest
    container_name: WEB_BAR_TFG_db
    environment:
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=malr07@
      - POSTGRES_DB=WEB_BAR_TFG_db
   
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bar_network

# Redes
networks:
  bar_network:
    driver: bridge