version: "3.9"

services:
  # Frontend (Vite + React)
  frontend:
    build: ./frontend  # Construye la imagen usando el Dockerfile dentro de ./frontend
    container_name: WEB_BAR_TFG_frontend  # Nombre del contenedor para identificarlo fácilmente
    ports:
      - "3000:3000"  # Mapea el puerto local 3000 con el puerto 3000 del contenedor (donde Vite se ejecuta)
    volumes:
      - ./frontend:/app  # Sincroniza el código local con el contenedor para desarrollo en vivo
      - /app/node_modules  # Evita sobrescribir node_modules al sincronizar la carpeta
    command: npm run dev  # Comando que lanza el servidor de desarrollo de Vite
    environment:
      - NODE_ENV=development  # Define el entorno como desarrollo
    depends_on:
      - backend  # Se asegura de que el backend esté disponible antes de iniciar
    networks:
      - bar_network  # Red para que los servicios puedan comunicarse entre sí

  # Backend (Node.js + Express)
  backend:
    build: ./backend
    container_name: WEB_BAR_TFG_backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    networks:
      - bar_network

  # Base de datos (PostgreSQL)
  db:
    image: postgres:latest
    container_name: WEB_BAR_TFG_db
    environment:
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=malr07@
      - POSTGRES_DB=WEB_BAR_TFG_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bar_network

# Redes
networks:
  bar_network:
    driver: bridge
